name: Allan Myles Photography
favicon: null
layout_spectrum: 0
typography_spectrum: 0.23986
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a1521'
    - '#dec3a9'
    - '#54636e'
    - '#a79c91'
    - '#797f83'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0
purpose: []
