analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0
  brandStrength: 0.4892473
  lightness: 0.5
  brandColors:
    - '#CFBEA4'
    - '#131D29'
    - '#A39B91'
    - '#F8DAD2'
  rhythmicContrast: 0
typography_spectrum: 0.5322581
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.5023
favicon: null
name: Allan Myles Photography
